apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octobox-beta-evidence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Rely on default storageClass (local-path) in k3s

