import { createPromiseClient } from '@connectrpc/connect';
import { createConnectTransport } from '@connectrpc/connect-web';
// Note: These will be generated by buf
// import { UserService } from '@/../../proto/gen/ts/user/v1/user_connect';

class GRPCClient {
  private transport: ReturnType<typeof createConnectTransport>;

  constructor() {
    this.transport = createConnectTransport({
      baseUrl: process.env.NEXT_PUBLIC_GRPC_URL || 'http://localhost:8080',
      credentials: 'include',
    });
  }

  async syncUserProfile(token: string) {
    // This will use the generated protobuf client once buf generates the files
    // For now, we'll use a direct HTTP call as a fallback
    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080'}/api/me`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (!response.ok) {
        throw new Error('Failed to sync profile');
      }

      return await response.json();
    } catch (error) {
      console.error('gRPC client error:', error);
      throw error;
    }
  }

  async updateUserProfile(token: string, data: {
    firstName?: string;
    lastName?: string;
    avatarUrl?: string;
  }) {
    // This will use the generated protobuf client once buf generates the files
    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080'}/api/me`,
        {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            first_name: data.firstName,
            last_name: data.lastName,
            avatar_url: data.avatarUrl,
          }),
        }
      );

      if (!response.ok) {
        throw new Error('Failed to update profile');
      }

      return await response.json();
    } catch (error) {
      console.error('gRPC client error:', error);
      throw error;
    }
  }
}

export const grpcClient = new GRPCClient();