"""Tests for tlog configuration and path isolation.

Verifies that:
1. tlog config path includes lab_id for isolation
2. tlog config disables input logging (security: no keystroke capture)
3. Volume names are per-lab (no shared volumes)
"""

import json
import pytest
from uuid import uuid4


def test_tlog_config_path_format():
    """Test that tlog session path follows expected format."""
    lab_id = str(uuid4())

    # Expected path format as configured in entrypoint.sh
    expected_path = f"/evidence/tlog/{lab_id}/session.jsonl"

    # Verify format
    assert lab_id in expected_path
    assert expected_path.startswith("/evidence/tlog/")
    assert expected_path.endswith("/session.jsonl")


def test_tlog_paths_are_unique_per_lab():
    """Test that different labs have different tlog paths."""
    lab1_id = str(uuid4())
    lab2_id = str(uuid4())

    path1 = f"/evidence/tlog/{lab1_id}/session.jsonl"
    path2 = f"/evidence/tlog/{lab2_id}/session.jsonl"

    assert path1 != path2
    assert lab1_id in path1
    assert lab2_id in path2
    assert lab1_id not in path2
    assert lab2_id not in path1


def test_tlog_config_structure():
    """Test the expected tlog config structure (as generated by entrypoint.sh)."""
    lab_id = str(uuid4())
    tlog_dir = f"/evidence/tlog/{lab_id}"

    # This is the config structure we expect entrypoint.sh to generate
    expected_config = {
        "shell": "/bin/bash",
        "writer": "file",
        "file": {
            "path": f"{tlog_dir}/session.jsonl"
        },
        "log": {
            "input": False,  # SECURITY: Must be False to avoid capturing passwords
            "output": True,
            "window": True
        },
        "limit": {
            "rate": 16384,
            "burst": 32768,
            "action": "drop"
        }
    }

    # Verify security-critical settings
    assert expected_config["log"]["input"] is False, "Input logging must be disabled for security"
    assert expected_config["log"]["output"] is True, "Output logging should be enabled"
    assert expected_config["writer"] == "file", "Should use file writer for persistence"


def test_tlog_config_no_input_logging():
    """SECURITY: Verify that tlog config explicitly disables input logging.

    Input logging would capture keystrokes including passwords, tokens, etc.
    This is a critical security requirement.
    """
    # The config generated by entrypoint.sh
    config = {
        "log": {
            "input": False,  # MUST be False
            "output": True,
            "window": True
        }
    }

    assert config["log"]["input"] is False, (
        "SECURITY VIOLATION: tlog input logging must be disabled to prevent "
        "capturing passwords and tokens typed by users"
    )


def test_compose_volume_names_per_lab():
    """Test that compose volume names are deterministic and per-lab."""
    lab1_id = uuid4()
    lab2_id = uuid4()

    # Project names as generated by ComposeLabRuntime
    project1 = f"octolab_{lab1_id}"
    project2 = f"octolab_{lab2_id}"

    # Volume names follow compose convention: <project>_<volume>
    evidence_vol1 = f"{project1}_lab_evidence"
    evidence_vol2 = f"{project2}_lab_evidence"

    pcap_vol1 = f"{project1}_lab_pcap"
    pcap_vol2 = f"{project2}_lab_pcap"

    home_vol1 = f"{project1}_octobox_home"
    home_vol2 = f"{project2}_octobox_home"

    # All volumes should be unique per lab
    assert evidence_vol1 != evidence_vol2
    assert pcap_vol1 != pcap_vol2
    assert home_vol1 != home_vol2

    # Verify lab_id is embedded in volume names
    assert str(lab1_id) in evidence_vol1
    assert str(lab2_id) in evidence_vol2


def test_no_static_volume_names():
    """Test that we don't use static volume names that would be shared."""
    lab_id = uuid4()
    project_name = f"octolab_{lab_id}"

    # These are the volume names we expect (project-scoped)
    evidence_vol = f"{project_name}_lab_evidence"
    pcap_vol = f"{project_name}_lab_pcap"
    home_vol = f"{project_name}_octobox_home"

    # Verify none of them are static/shared names
    assert evidence_vol != "lab_evidence"
    assert evidence_vol != "octolab_lab_evidence"
    assert pcap_vol != "lab_pcap"
    assert home_vol != "octobox_home"

    # Verify they all contain the lab_id
    assert str(lab_id) in evidence_vol
    assert str(lab_id) in pcap_vol
    assert str(lab_id) in home_vol


def test_tlog_dir_permissions_expected():
    """Document expected tlog directory permissions (set by entrypoint.sh)."""
    # entrypoint.sh creates the tlog directory with these permissions:
    # mkdir -p "$TLOG_DIR"
    # chown -R pentester:pentester "$TLOG_DIR"
    # chmod 770 "$TLOG_DIR"

    expected_perms = 0o770  # rwxrwx---

    # This documents the expected behavior for manual verification
    assert expected_perms == 0o770, "tlog directory should be 770 (rwxrwx---)"


def test_lab_id_fallback_to_unknown():
    """Test that missing LAB_ID falls back to 'unknown' (as per entrypoint.sh)."""
    # entrypoint.sh behavior:
    # LAB_ID="${LAB_ID:-unknown}"
    # if [ "$LAB_ID" = "default" ] || [ -z "$LAB_ID" ]; then
    #     LAB_ID="unknown"
    # fi

    def simulate_entrypoint_lab_id(env_lab_id):
        """Simulate entrypoint.sh LAB_ID logic."""
        lab_id = env_lab_id if env_lab_id else "unknown"
        if lab_id == "default" or not lab_id:
            lab_id = "unknown"
        return lab_id

    # Test various inputs
    assert simulate_entrypoint_lab_id(None) == "unknown"
    assert simulate_entrypoint_lab_id("") == "unknown"
    assert simulate_entrypoint_lab_id("default") == "unknown"
    assert simulate_entrypoint_lab_id("abc-123") == "abc-123"

    # A real UUID should be passed through
    real_id = str(uuid4())
    assert simulate_entrypoint_lab_id(real_id) == real_id
